package frc.robot.annotation;

import org.littletonrobotics.junction.Logger;

import frc.robot.RobotContainer;

public class AutoLogMAVSFINAL {
  // Generated by MavsAnnotationProcessor
  @AutoLogDisabler(indexesToBlock = {})
  public static void runMAVSLogging(RobotContainer robotContainer) {
    Logger.recordOutput("Drive/Odometry/Robot", robotContainer.drive.getPose());
    Logger.recordOutput("Drive/HELLO", robotContainer.drive.getRotation());
  }
}
